# [theme]
# font = "'Work Sans':https://fonts.googleapis.com/css2?family=Work+Sans:wght@300;400;500;600;700&display=swap"
# primaryColor = "#FF4B4B"
# backgroundColor = "#0E1117"
# secondaryBackgroundColor = "#333333"
# textColor = "#FAFAFA"
# font = "sans serif"

# [theme]
# font = "'Work Sans':https://fonts.googleapis.com/css2?family=Work+Sans:wght@300;400;500;600;700&display=swap"
# baseRadius = "12px"

[theme]
primaryColor = "#00f5d4"
backgroundColor = "#11141c"
secondaryBackgroundColor = "#1e222b"
textColor = "#ffffff"
font = "sans serif"
# 101420
